CanTeenVLU/CanTeenVLU/Models/CATEGORY.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanTeenVLU.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.FOODs = new HashSet<FOOD>();
        }
    
        public int ID { get; set; }
        public string CATEGORY_CODE { get; set; }
        [Required(ErrorMessage = "Bắt buộc phải điền")]
        [MinLength(6, ErrorMessage = "Nhập tối thiểu 6 kí tự")]
        [MaxLength(20, ErrorMessage = " Nhập tối thiểu 20 kí tự")]
        public string CATEGORY_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOD> FOODs { get; set; }
    }
}

CanTeenVLU/CanTeenVLU/Areas/Admin/Controllers/CATEGORiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using CanTeenVLU.Areas.Admin.Middleware;
using CanTeenVLU.Models;

namespace CanTeenVLU.Areas.Admin.Controllers
{
    [LoginVerification]
    public class CATEGORiesController : Controller
    {
        private QUANLYCANTEENEntities db = new QUANLYCANTEENEntities();
        private const string PICTURE_PATH = "~/Upload/Categories/";


        // GET: Admin/CATEGORies
        public ActionResult Index()
        {
            return View(db.CATEGORies.ToList());
        }

        // GET: Admin/CATEGORies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            if (cATEGORY == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORY);
        }
        public ActionResult Picture(int id)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + id, "images");
        }

        // GET: Admin/CATEGORies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/CATEGORies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CATEGORY_CODE,CATEGORY_NAME,IMAGE_URL,STATUS")] CATEGORY cATEGORY, HttpPostedFileBase picture)
        {
            var product = new CATEGORY();
            if (picture != null)
            {
                using (var scope = new TransactionScope())
                {
                    product.CATEGORY_CODE = cATEGORY.CATEGORY_CODE;
                    product.CATEGORY_NAME = cATEGORY.CATEGORY_NAME;
                    product.STATUS = cATEGORY.STATUS;
                    db.CATEGORies.Add(product);
                    db.SaveChanges();

                    var path = Server.MapPath(PICTURE_PATH);
                    picture.SaveAs(path + product.ID);
                    scope.Complete();
                }
            }
            else
            {
                ModelState.AddModelError("", "Picture not found!");
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/CATEGORies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            if (cATEGORY == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORY);
        }

        // POST: Admin/CATEGORies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CATEGORY_CODE,CATEGORY_NAME,IMAGE_URL,STATUS")]int id, CATEGORY cATEGORY, HttpPostedFileBase picture)
        {
            var product = db.CATEGORies.Find(id);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    product.ID = cATEGORY.ID;
                    product.CATEGORY_CODE = cATEGORY.CATEGORY_CODE;
                    product.CATEGORY_NAME = cATEGORY.CATEGORY_NAME;
                    product.STATUS = cATEGORY.STATUS;

                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();

                    if (picture != null)
                    {
                        //System.IO.File.WriteAllText(@"D:\test.txt", "ok");
                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + cATEGORY.ID);
                    }

                    scope.Complete();
                    return RedirectToAction("Index");

                }
            }
            return View(cATEGORY);
        }

        // GET: Admin/CATEGORies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            if (cATEGORY == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORY);
        }

        // POST: Admin/CATEGORies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            db.CATEGORies.Remove(cATEGORY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CanTeenVLU/CanTeenVLU/Areas/Admin/Views/CATEGORies/Create.cshtml
@model CanTeenVLU.Models.CATEGORY

@{
    ViewBag.Title = "Tạo danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Create", "CATEGORies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2 style="font-family:'Times New Roman', Times, serif">Tạo mới danh mục món ăn</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Tên danh mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORY_NAME, new { htmlAttributes = new { @class = "form-control", @required = true, @minLenght = "6", @maxLenght = "50" } })
                @Html.ValidationMessageFor(model => model.CATEGORY_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Hình ảnh</label>
            <div class="col-md-10">
                <input class="form-control" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                <img id="Picture" width="300" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Trạng thái</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.STATUS)
                    @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-default" style="border-radius:12px" /> |
                @Html.ActionLink("Trở lại", "Index")
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readPicture(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('img#Picture').attr('src', e.target.result).width(200).height(250);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

CanTeenVLU/CanTeenVLU/Areas/Admin/Views/CATEGORies/Delete.cshtml
@model CanTeenVLU.Models.CATEGORY

@{
    ViewBag.Title = "Xoá danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h3 style="font-family:'Times New Roman', Times, serif">Bạn có chắc chắn muốn xoá mục này không?</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Mã danh mục</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_CODE)
        </dd>

        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Tên danh mục</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_NAME)
        </dd>

        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Hình ảnh</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE_URL)
        </dd>

        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Trạng thái</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoá" class="btn btn-default" /> |
            @Html.ActionLink("Trở lại", "Index")
        </div>
    }
</div>

CanTeenVLU/CanTeenVLU/Areas/Admin/Views/CATEGORies/Details.cshtml
@model CanTeenVLU.Models.CATEGORY

@{
    ViewBag.Title = "Chi tiết";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div>
    <h2 style="font-family:'Times New Roman', Times, serif">Chi tiết danh mục món ăn</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Mã danh mục</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_CODE)
        </dd>

        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Tên danh mục</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_NAME)
        </dd>

        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Hình ảnh</label>
        </dt>

        <dd>
            <img id="Picture" src="@Url.Action("Picture", new { Model.ID})" width="300" />
        </dd>

        <dt>
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Trạng thái</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Trở lại", "Index")
</p>

CanTeenVLU/CanTeenVLU/Areas/Admin/Views/CATEGORies/Edit.cshtml
@model CanTeenVLU.Models.CATEGORY

@{
    ViewBag.Title = "Chỉnh sửa";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Edit", "CATEGORies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2 style="font-family:'Times New Roman', Times, serif">Chỉnh sửa danh mục món ăn</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORY_CODE, new { htmlAttributes = new { @class = "form-control", @requied = true, @readonly = true } })
                @Html.ValidationMessageFor(model => model.CATEGORY_CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Tên danh mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORY_NAME, new { htmlAttributes = new { @class = "form-control", @required = true, @minLenght = "6", @maxLenght = "50" } })
                @Html.ValidationMessageFor(model => model.CATEGORY_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Hình ảnh</label>
            <div class="col-md-10">
                <input class="form-control" type="file" name="picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                <img id="picture" src="@Url.Action("Picture", new { Model.ID})" width="250" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" style="font-family:'Times New Roman', Times, serif" for="IMG">Trạng thái</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.STATUS)
                    @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" /> | @Html.ActionLink("Trở lại", "Index")
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readPicture(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('img#Picture').attr('src', e.target.result).width(200).height(250);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

CanTeenVLU/CanTeenVLU/Areas/Admin/Views/CATEGORies/Index.cshtml
@model IEnumerable<CanTeenVLU.Models.CATEGORY>

@{
    ViewBag.Title = "Loại món ăn";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="font-family:'Times New Roman', Times, serif">Danh sách loại món ăn</h2>

<button style="border-radius:24px; font-family:'Times New Roman', Times, serif">
    @Html.ActionLink("Tạo mới", "Create")
</button>

<hr />

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title" style="font-family:'Times New Roman', Times, serif">Bảng danh sách các loại món ăn</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped" style="text-align:center">
                        <thead>
                            <tr style="font-family:'Times New Roman', Times, serif">
                                <th>Mã loại món ăn</th>
                                <th>Tên món ăn</th>
                                <th>Hình ảnh</th>
                                <th>Trạng thái</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr style="text-align:center">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CATEGORY_CODE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CATEGORY_NAME)
                                    </td>
                                    <td>
                                        <img src="@Url.Action("Picture", new { item.ID})" width="100" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.STATUS)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) |
                                        @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                                        @Html.ActionLink("Xoá", "Delete", new { id = item.ID }, new { onclick = "return confirm('Bạn có chắc chắn muốn xoá không?');" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr style="font-family:'Times New Roman', Times, serif">
                                <th>Mã loại món ăn</th>
                                <th>Tên món ăn</th>
                                <th>Hình ảnh</th>
                                <th>Trạng thái</th>
                                <th>Hành động</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>