CanTeenVLU/CanTeenVLU/Models/ORDER_DETAIL.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanTeenVLU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int ID { get; set; }
        public int ORDER_ID { get; set; }
        public int MENU_ID { get; set; }
        public int QUANTITY { get; set; }
        public int PRICE { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}

CanTeenVLU/CanTeenVLU/Areas/Admin/Controllers/FOODsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using CanTeenVLU.Areas.Admin.Middleware;
using CanTeenVLU.Models;

namespace CanTeenVLU.Areas.Admin.Controllers
{
    [LoginVerification]
    public class FOODsController : Controller
    {
        private QUANLYCANTEENEntities db = new QUANLYCANTEENEntities();
        private const string PICTURE_PATH = "~/Upload/Foods/";

        // GET: Admin/FOODs
        public ActionResult Index()
        {
            var fOODs = db.FOODs.Include(f => f.CATEGORY);
            return View(fOODs.ToList());
        }
        public ActionResult Picture(int id)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + id, "images");
        }

        //for customers to view products
        [AllowAnonymous]
        public ActionResult Index2()
        {
            var model = db.FOODs.ToList();
            return View(model);
        }

        // GET: Admin/FOODs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FOOD fOOD = db.FOODs.Find(id);
            if (fOOD == null)
            {
                return HttpNotFound();
            }
            return View(fOOD);
        }

        // GET: Admin/FOODs/Create
        public ActionResult Create()
        {
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE");
            return View();
        }

        // POST: Admin/FOODs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FOOD_CODE,FOOD_NAME,CATEGORY_ID,DESCRIPTION,PRICE,IMAGE_URL,STATUS")] FOOD fOOD, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                var product = new FOOD();
                if (picture != null)
                {
                    using (var scope = new TransactionScope())
                    {
                        product.ID = fOOD.ID;
                        product.FOOD_CODE = fOOD.FOOD_CODE;
                        product.FOOD_NAME = fOOD.FOOD_NAME;
                        product.CATEGORY_ID = fOOD.CATEGORY_ID;
                        product.DESCRIPTION = fOOD.DESCRIPTION;
                        product.PRICE = fOOD.PRICE;
                        product.STATUS = fOOD.STATUS;
                        db.FOODs.Add(product);
                        db.SaveChanges();

                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + product.ID);

                        scope.Complete();
                    }
                }
                else ModelState.AddModelError("", "Hình ảnh không được tìm thấy");
            }
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE", fOOD.CATEGORY_ID);
            return RedirectToAction("Index");
        }

        // GET: Admin/FOODs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FOOD fOOD = db.FOODs.Find(id);
            if (fOOD == null)
            {
                return HttpNotFound();
            }
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE", fOOD.CATEGORY_ID);
            return View(fOOD);
        }

        // POST: Admin/FOODs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "ID,FOOD_CODE,FOOD_NAME,CATEGORY_ID,DESCRIPTION,PRICE,IMAGE_URL,STATUS")] FOOD fOOD, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                var product = db.FOODs.Find(id);
                if (ModelState.IsValid)
                {
                    using (var scope = new TransactionScope())
                    {
                        product.ID = fOOD.ID;
                        product.FOOD_CODE = fOOD.FOOD_CODE;
                        product.FOOD_NAME = fOOD.FOOD_NAME;
                        product.CATEGORY_ID = fOOD.CATEGORY_ID;
                        product.DESCRIPTION = fOOD.DESCRIPTION;
                        product.PRICE = fOOD.PRICE;
                        product.STATUS = fOOD.STATUS;

                        db.Entry(product).State = EntityState.Modified;
                        db.SaveChanges();

                        if (picture != null)
                        {
                            var path = Server.MapPath(PICTURE_PATH);
                            picture.SaveAs(path + product.ID);
                        }

                        scope.Complete();
                        return RedirectToAction("Index");

                    }
                }
                db.Entry(fOOD).State = EntityState.Modified;
            }
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE", fOOD.CATEGORY_ID);
            return View(fOOD);
        }

        // GET: Admin/FOODs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FOOD fOOD = db.FOODs.Find(id);
            if (fOOD == null)
            {
                return HttpNotFound();
            }
            return View(fOOD);
        }

        // POST: Admin/FOODs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FOOD fOOD = db.FOODs.Find(id);
            db.FOODs.Remove(fOOD);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CanTeenVLU/CanTeenVLU/Areas/Customer/Controllers/ORDER_DETAILController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CanTeenVLU.Models;

namespace CanTeenVLU.Areas.Customer.Controllers
{
    public class ORDER_DETAILController : Controller
    {
        private QUANLYCANTEENEntities db = new QUANLYCANTEENEntities();

        private List<MENU> ShoppingCart = null;

        private void GetShoppingCart()
        {
            if (Session["ShoppingCart"] != null)
                ShoppingCart = Session["ShoppingCart"] as List<MENU>;
            else
            {
                ShoppingCart = new List<MENU>();
                Session["ShoppingCart"] = ShoppingCart;
            }
        }
        // GET: ShoppingCart
        public ActionResult Index()
        {
            GetShoppingCart();
            var hashtable = new Hashtable();
            foreach (var billDetail in ShoppingCart)
            {
                if (hashtable[billDetail.FOOD.ID] != null)
                {
                    (hashtable[billDetail.FOOD.ID] as MENU).QUANTITY += billDetail.QUANTITY;
                }
                else hashtable[billDetail.FOOD.ID] = billDetail;
            }

            ShoppingCart.Clear();
            foreach (MENU billDetail in hashtable.Values)
                ShoppingCart.Add(billDetail);
            return View(ShoppingCart);
        }

        // GET: ShoppingCart/Create
        public ActionResult Create(int productId, int quantity)
        {
            GetShoppingCart();
            var product = db.FOODs.Find(productId);
            ShoppingCart.Add(new MENU
            {
                FOOD = product,
                QUANTITY = quantity
            });

            return RedirectToAction("Index");
        }

        // GET: ShoppingCart/Edit/5
        [HttpPost]
        public ActionResult Edit(int[] product_id, int[] quantity)
        {
            GetShoppingCart();
            ShoppingCart.Clear();
            if (product_id != null)
                for (int i = 0; i < product_id.Length; i++)
                    if (quantity[i] > 0)
                    {
                        var product = db.FOODs.Find(product_id[i]);
                        ShoppingCart.Add(new MENU
                        {
                            FOOD = product,
                            QUANTITY = quantity[i]
                        });
                    }
            Session["ShoppingCart"] = ShoppingCart;

            return RedirectToAction("Index");
        }

        // GET: ShoppingCart/Delete/5
        public ActionResult Delete()
        {
            GetShoppingCart();
            ShoppingCart.Clear();
            Session["ShoppingCart"] = ShoppingCart;
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CanTeenVLU/CanTeenVLU/Areas/Customer/Views/ORDER_DETAIL/Create.cshtml
@model CanTeenVLU.Models.ORDER_DETAIL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ORDER_DETAIL</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ORDER_ID, "ORDER_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ORDER_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ORDER_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MENU_ID, "MENU_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MENU_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MENU_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QUANTITY, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QUANTITY, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PRICE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PRICE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

CanTeenVLU/CanTeenVLU/Areas/Customer/Views/ORDER_DETAIL/Delete.cshtml
@model CanTeenVLU.Models.ORDER_DETAIL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ORDER_DETAIL</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.QUANTITY)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.QUANTITY)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PRICE)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PRICE)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MENU.ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MENU.ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ORDER.ORDER_CODE)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ORDER.ORDER_CODE)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

CanTeenVLU/CanTeenVLU/Areas/Customer/Views/ORDER_DETAIL/Details.cshtml
@model CanTeenVLU.Models.ORDER_DETAIL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>ORDER_DETAIL</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.QUANTITY)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.QUANTITY)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PRICE)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PRICE)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MENU.ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MENU.ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ORDER.ORDER_CODE)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ORDER.ORDER_CODE)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

CanTeenVLU/CanTeenVLU/Areas/Customer/Views/ORDER_DETAIL/Edit.cshtml
@model CanTeenVLU.Models.ORDER_DETAIL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>ORDER_DETAIL</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.ORDER_ID, "ORDER_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ORDER_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ORDER_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MENU_ID, "MENU_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MENU_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MENU_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.QUANTITY, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QUANTITY, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PRICE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PRICE, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

CanTeenVLU/CanTeenVLU/Areas/Customer/Views/ORDER_DETAIL/Index.cshtml
@model IEnumerable<CanTeenVLU.Models.MENU>

@{
    Layout = null;
    var Subtotal = 0;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | CanTeen Văn Lang</title>
    <link href="~/backend/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/backend/css/prettyPhoto.css" rel="stylesheet" />
    <link href="~/backend/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/backend/css/price-range.css" rel="stylesheet" />
    <link href="~/backend/css/animate.css" rel="stylesheet" />
    <link href="~/backend/css/main.css" rel="stylesheet" />
    <link href="~/backend/css/responsive.css" rel="stylesheet" />
    @*[if lt IE 9]>*@
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    @*<![endif]*@
    <link rel="shortcut icon" href="@Url.Content("~/images/ico/favicon.ico")">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="@Url.Content("~/images/ico/apple-touch-icon-144-precomposed.png")">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="@Url.Content("~/images/ico/apple-touch-icon-114-precomposed.png")">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="@Url.Content("~/images/ico/apple-touch-icon-72-precomposed.png")">
    <link rel="apple-touch-icon-precomposed" href="@Url.Content("~/images/ico/apple-touch-icon-57-precomposed.png")">
</head><!--/head-->

<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="index.html"><img src="images/home/logo.png" alt="" /></a>
                        </div>
                        <div class="btn-group pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    VN
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">US</a></li>
                                    <li><a href="#">UK</a></li>
                                </ul>
                            </div>

                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    VND
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">EUR</a></li>
                                    <li><a href="#">USD</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-user"></i>Tài khoản</a></li>
                                <li><a href="#"><i class="fa fa-star"></i>Yêu thích</a></li>
                                <li><a href="/Customer/ORDER_DETAIL/"><i class="fa fa-shopping-cart"></i>Giỏ hàng</a></li>
                                <li><a href="/Admin/Auth/Logout"><i class="fa fa-lock"></i>Đăng xuất</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="/Customer/FOODS/" class="active">Trang chủ</a></li>
                                <li><a href="/Customer/FOODS/">Thực đơn</a></li>
                                <li class="dropdown">
                                    <a href="#">Thông tin<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
                                        <li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right">
                            <input type="text" placeholder="Tìm" />
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->

    <section id="cart_items">
        <div class="container">
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                        <tr class="cart_menu">
                            <td class="image">Hình ảnh</td>
                            <td class="name">Tên món ăn</td>
                            <td class="price">Giá (VND)</td>
                            <td class="quantity">Số lượng</td>
                            <td class="total">Thành tiền</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            Subtotal += item.FOOD.PRICE * item.QUANTITY;
                            <tr>
                                <td class="cart_product">
                                    <a href="@Url.Action("Details", "FOODs", new { item.FOOD.ID })"><img src="@Url.Action("Picture", "FOODs", new { item.FOOD.ID })" alt="" width="140" height="110"></a>
                                </td>
                                <td class="cart_description">
                                    <a href="@Url.Action("Details", "FOODs", new { item.FOOD.ID })">
                                        <h4>@item.FOOD.FOOD_NAME</h4>
                                    </a>
                                    <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font></font></p>
                                </td>
                                <td class="cart_price">
                                    <p><font style="vertical-align: inherit;">@item.FOOD.PRICE.ToString("N0")<font style="vertical-align: inherit;"></font></font></p>
                                </td>
                                <td class="cart_quantity">
                                    <div class="cart_quantity_button">
                                        @Html.Hidden("FOOD_ID", item.FOOD.ID)
                                        <a class="fa-google-plus-g" href=""><font style="vertical-align: inherit;"> + </font></a>
                                        <input class="cart_quantity_input" type="text" name="quantity" value="@item.QUANTITY" autocomplete="off" size="2">
                                        <a class="cart_quantity_down" href=""><font style="vertical-align: inherit;"> - </font></a>
                                    </div>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@((item.FOOD.PRICE * item.QUANTITY).ToString("N0"))</font></font></p>
                                </td>
                                <td class="cart_delete">
                                    <a class="cart_quantity_delete" href="@Url.Action("Delete", "ORDER_DETAIL")"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                @foreach (var item in Model)
                {
                    <div class="col-sm-6">
                        <div class="total_area">
                            <ul>
                                <li>Số lượng<span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.QUANTITY</font></font></span></li>
                                <li>Thành tiền<span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@((item.FOOD.PRICE * item.QUANTITY).ToString("N0")) VND</font></font></span></li>
                            </ul>
                            <a class="btn btn-default update" href="">Cập nhật</a>
                            <a class="btn btn-default check_out" href="@Url.Action("Index", "FOODs")">Tiếp tục</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section> <!--/#cart_items-->

    <a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647;"><i class="fa fa-angle-up"></i></a>

    <script src="~/Scripts/js/jquery.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/jquery.scrollUp.min.js"></script>
    <script src="~/Scripts/js/price-range.js"></script>
    <script src="~/Scripts/js/jquery.prettyPhoto.js"></script>
    <script src="~/Scripts/js/main.js"></script>
</body>
</html>